#!/bin/bash
# Update package lists
apt-get update
apt-get install -y nginx
sed -i 's/^\(listen\s\+\)[0-9]\+/\180/' /etc/nginx/sites-available/default
/etc/init.d/nginx restart
echo "Hello World!" > /var/www/html/index.nginx-debian.html
