#!/usr/bin/env bash
# this is nginx listening debug

PORT_NUMBER=8080
sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup
sudo sh -c "cat <<EOF >> /etc/nginx/nginx.conf
server {
    listen $PORT_NUMBER;
    server_name localhost;
}
EOF"
sudo nginx -t
if [ $? -eq 0 ]; then
    sudo systemctl reload nginx
else
    sudo cp /etc/nginx/nginx.conf.backup /etc/nginx/nginx.conf
fi
sudo rm /etc/nginx/nginx.conf.backup
