#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install ufw

# Allow SSH, HTTP, and HTTPS
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable UFW
sudo ufw enable

# Check UFW status
sudo ufw status
